In [1]:
import pandas as pd
from bs4 import BeautifulSoup as bs
import urllib.request
import time
import random
import re

In [2]:
url = "https://www.getcompanyinfo.com/industry/information-technology-services/"
html = urllib.request.urlopen(url).read().decode('utf-8')
soup = bs(html)

In [3]:
Company = []
Link = []
Type = []
Industry = []
Founded = []
Country = []
City = []
State = []
Phone = []
Email = []
Website = []
Employees = []


Companies = [x.get_text() for x in soup.find_all(title = "Company Name")]
Links = [x['href'] for x in soup.find_all(title = "Company Name")]
url_base = "https://www.getcompanyinfo.com"


for n in range(len(Companies)):
    html2 = urllib.request.urlopen(url_base+Links[n]).read().decode('utf-8')
    soup2 = bs(html2)
    Company.append(Companies[n])
    Link.append(Links[n])
    Type.append(soup2.find("label",text="Company Type:").find_next_sibling().get_text())
    Industry.append(soup2.find("label",text="Industry:").find_next_sibling().get_text())
    Founded.append(soup2.find("label",text="Founded:").find_next_sibling().get_text())
    Country.append(soup2.find("label",text="Country:").find_next_sibling().get_text())
    cityState = soup2.find("label",text="Headquarter:").find_next_sibling().get_text()
    split = cityState.split(",")
    City.append(split[0])
    State.append(split[1].strip())
    Phone.append(soup2.find("label",text="Phone:").find_next_sibling().get_text())
    Email.append(soup2.find("label",text="Email:").find_next_sibling().get_text())
    Website.append(soup2.find("label",text="Website:").find_next_sibling().get_text())
    Employees.append(soup2.find("h4",text="Employees").find_next_sibling().get_text())

AttributeError: 'NoneType' object has no attribute 'find_next_sibling'

In [4]:
Companies[n]

'Hewlett Packard Enterprise'

In [6]:
Company = []
Link = []
Type = []
Industry = []
Founded = []
Country = []
City = []
State = []
Phone = []
Email = []
Website = []
Employees = []

Companies = [x.get_text() for x in soup.find_all(title = "Company Name")]
Links = [x['href'] for x in soup.find_all(title = "Company Name")]
url_base = "https://www.getcompanyinfo.com"


for n in range(len(Companies)):
    html2 = urllib.request.urlopen(url_base+Links[n]).read().decode('utf-8')
    soup2 = bs(html2)
    Company.append(Companies[n])
    Link.append(Links[n])
    try:
        Type.append(soup2.find("label",text="Company Type:").find_next_sibling().get_text())
    except:
        Type.append(None)
    try:
        Industry.append(soup2.find("label",text="Industry:").find_next_sibling().get_text())
    except:
        Industry.append(None)
    try:
        Founded.append(soup2.find("label",text="Founded:").find_next_sibling().get_text())
    except:
        Founded.append(None)
    try:
        Country.append(soup2.find("label",text="Country:").find_next_sibling().get_text())
    except:
        Country.append(None)
    try:
        cityState = soup2.find("label",text="Headquarter:").find_next_sibling().get_text()
        split = cityState.split(",")
        City.append(split[0])
        State.append(split[1])
    except:
        City.append(None)
        State.append(None)
    try:
        Phone.append(soup2.find("label",text="Phone:").find_next_sibling().get_text())
    except:
        Phone.append(None)
    try:
        Email.append(soup2.find("label",text="Email:").find_next_sibling().get_text())
    except:
        Email.append(None)
    try:
        Website.append(soup2.find("label",text="Website:").find_next_sibling().get_text())
    except:
        Website.append(None)
    try:
        Employees.append(soup2.find("h4",text="Employees").find_next_sibling().get_text())
    except:
        Employees.append(None)

In [7]:
pd.DataFrame({"Company":Company,
             "Link":Link,
             "Type":Type,
             "Industry":Industry,
             "Founded":Founded,
             "Country":Country,
             "City":City,
             "State":State,
             "Phone":Phone,
             "Email":Email,
             "Website":Website,
             "Employees":Employees})

,Company,Link,Type,Industry,Founded,Country,City,State,Phone,Email,Website,Employees
0,Accenture,/company/accenture/,Public,Information Technology & Services,1989,Ireland,Dublin 2,County Dublin,35316462000,careersph@accenture.com,http://www.accenture.com,Above 10000
1,Tata Consultancy Services,/company/tata-consultancy-services/,Public,Information Technology & Services,1968,India,Mumbai,Maharashtra,912267789999,contact.us@tcs.com,https://www.tcs.com/,Above 10000
2,Ernst & Young,/company/ernst-young/,Private,Information Technology & Services,1989,United Kingdom,London,Greater London,442079512000,sholt2@uk.ey.com,http://ey.com,Above 10000
3,Cognizant,/company/cognizant/,Public,Information Technology & Services,1994,United States,Teaneck,New Jersey,12018010233,inquiry@cognizant.com,https://www.cognizant.com,Above 10000
4,Infosys,/company/infosys/,Public,Information Technology & Services,1981,India,Bangalore,Karnataka,918028520261,investors@infosys.com,https://www.infosys.com/,Above 10000
5,Hewlett Packard Enterprise,/company/hewlett-packard-enterprise/,Public,Information Technology & Services,1939,United States,San Jose,California,None,None,https://www.hpe.com,Above 10000
6,Capgemini,/company/capgemini/,Public,Information Technology & Services,1967,France,Paris,Paris,33147545000,info.me@capgemini.com,https://www.capgemini.com,Above 10000
7,Wipro,/company/wipro/,Public,Information Technology & Services,1945,India,Bangalore,Karnataka,918028440011,info@wipro.com,http://www.wipro.com,Above 10000
8,Oracle,/company/oracle/,Public,Information Technology & Services,1977,United States,Redwood Shores,California,18006330738,oracle-acct_ww@oracle.com,https://www.oracle.com/,Above 10000
9,HCL Technologies,/company/hcl-technologies/,Public,Information Technology & Services,1976,India,Noida,Uttar Pradesh,None,None,https://www.hcltech.com/,Above 10000
10,Verizon Communications,/company/verizon-communications/,Public,Information Technology & Services,1983,United States,New York,New York,None,None,https://www.verizon.com/,Above 10000
11,Dell,/company/dell/,Private,Information Technology & Services,1984,United States,Round Rock,Texas,None,None,http://www.dell.com,Above 10000

Now we need to tackle the next page.

In [10]:
# Code for next page
soup.find_all("ul", class_="pagination")
soup.find("ul",class_="pagination")

<ul class="pagination">
<li class="disabled"><a href="#">«</a></li>
<li class="active"><a href="?page=1">1 <span class="sr-only">(current)</span></a>
</li>
<li><a href="?page=2">2</a></li>
<li><a href="?page=3">3</a></li>
<li><a href="?page=4">4</a></li>
<li><a href="?page=5">5</a></li>
<li><a href="?page=6">6</a></li>
<li><a href="?page=2">»</a></li>
</ul>

In [16]:
soup.find("ul",class_="pagination").find_all("li")[-1].findChild()["href"]
soup.find("ul",class_="pagination").find_all("a")[-1]["href"]

'?page=2'

In [17]:
Company = []
Link = []
Type = []
Industry = []
Founded = []
Country = []
City = []
State = []
Phone = []
Email = []
Website = []
Employees = []
url = "https://www.getcompanyinfo.com/industry/information-technology-services/"
Next = "?page=1"

while Next != "?page=3":#"#":
    print(Next)
    html = urllib.request.urlopen(url+Next).read().decode('utf-8')
    soup = bs(html)
    
    Companies = [x.get_text() for x in soup.find_all(title = "Company Name")]
    Links = [x['href'] for x in soup.find_all(title = "Company Name")]
    url_base = "https://www.getcompanyinfo.com"

    for n in range(len(Companies)):
        html2 = urllib.request.urlopen(url_base+Links[n]).read().decode('utf-8')
        soup2 = bs(html2)
        Company.append(Companies[n])
        Link.append(Links[n])
        try:
            Type.append(soup2.find("label",text="Company Type:").find_next_sibling().get_text())
        except:
            Type.append(None)
        try:
            Industry.append(soup2.find("label",text="Industry:").find_next_sibling().get_text())
        except:
            Industry.append(None)
        try:
            Founded.append(soup2.find("label",text="Founded:").find_next_sibling().get_text())
        except:
            Founded.append(None)
        try:
            Country.append(soup2.find("label",text="Country:").find_next_sibling().get_text())
        except:
            Country.append(None)
        try:
            cityState = soup2.find("label",text="Headquarter:").find_next_sibling().get_text()
            split = cityState.split(",")
            City.append(split[0])
            State.append(split[1])
        except:
            City.append(None)
            State.append(None)
        try:
            Phone.append(soup2.find("label",text="Phone:").find_next_sibling().get_text())
        except:
            Phone.append(None)
        try:
            Email.append(soup2.find("label",text="Email:").find_next_sibling().get_text())
        except:
            Email.append(None)
        try:
            Website.append(soup2.find("label",text="Website:").find_next_sibling().get_text())
        except:
            Website.append(None)
        try:
            Employees.append(soup2.find("h4",text="Employees").find_next_sibling().get_text())
        except:
            Employees.append(None)
    Next = soup.find("ul",class_="pagination").find_all("a")[-1]["href"]
    
    time.sleep(random.uniform(5,15))
print("Done!")

?page=1
?page=2
Done!

In [18]:
df=pd.DataFrame({"Company":Company,
             "Link":Link,
             "Type":Type,
             "Industry":Industry,
             "Founded":Founded,
             "Country":Country,
             "City":City,
             "State":State,
             "Phone":Phone,
             "Email":Email,
             "Website":Website,
             "Employees":Employees})

In [19]:
df

,Company,Link,Type,Industry,Founded,Country,City,State,Phone,Email,Website,Employees
0,Accenture,/company/accenture/,Public,Information Technology & Services,1989,Ireland,Dublin 2,County Dublin,35316462000,careersph@accenture.com,http://www.accenture.com,Above 10000
1,Tata Consultancy Services,/company/tata-consultancy-services/,Public,Information Technology & Services,1968,India,Mumbai,Maharashtra,912267789999,contact.us@tcs.com,https://www.tcs.com/,Above 10000
2,Ernst & Young,/company/ernst-young/,Private,Information Technology & Services,1989,United Kingdom,London,Greater London,442079512000,sholt2@uk.ey.com,http://ey.com,Above 10000
3,Cognizant,/company/cognizant/,Public,Information Technology & Services,1994,United States,Teaneck,New Jersey,12018010233,inquiry@cognizant.com,https://www.cognizant.com,Above 10000
4,Infosys,/company/infosys/,Public,Information Technology & Services,1981,India,Bangalore,Karnataka,918028520261,investors@infosys.com,https://www.infosys.com/,Above 10000
5,Hewlett Packard Enterprise,/company/hewlett-packard-enterprise/,Public,Information Technology & Services,1939,United States,San Jose,California,None,None,https://www.hpe.com,Above 10000
6,Capgemini,/company/capgemini/,Public,Information Technology & Services,1967,France,Paris,Paris,33147545000,info.me@capgemini.com,https://www.capgemini.com,Above 10000
7,Wipro,/company/wipro/,Public,Information Technology & Services,1945,India,Bangalore,Karnataka,918028440011,info@wipro.com,http://www.wipro.com,Above 10000
8,Oracle,/company/oracle/,Public,Information Technology & Services,1977,United States,Redwood Shores,California,18006330738,oracle-acct_ww@oracle.com,https://www.oracle.com/,Above 10000
9,HCL Technologies,/company/hcl-technologies/,Public,Information Technology & Services,1976,India,Noida,Uttar Pradesh,None,None,https://www.hcltech.com/,Above 10000
10,Verizon Communications,/company/verizon-communications/,Public,Information Technology & Services,1983,United States,New York,New York,None,None,https://www.verizon.com/,Above 10000
11,Dell,/company/dell/,Private,Information Technology & Services,1984,United States,Round Rock,Texas,None,None,http://www.dell.com,Above 10000
12,Genpact,/company/genpact/,Public,Information Technology & Services,1997,United States,New York,New York,12128966600,hr.helpdeskexit@genpact.com,http://www.genpact.com,Above 10000
13,DXC Technology,/company/dxc-technology/,Public,Information Technology & Services,2017,United States,Tysons,Virginia,None,None,https://www.dxc.technology,Above 10000
14,HP,/company/hp/,Public,Information Technology & Services,1939,United States,Palo Alto,California,18001084747,hhocustomerdelivery@hp.com,http://www.hp.com/,Above 10000
15,Dell EMC,/company/dell-emc/,Private,Information Technology & Services,1979,United States,Hopkinton,Massachusetts,None,None,http://www.dellemc.com,Above 10000
16,CenturyLink,/company/centurylink/,Public,Information Technology & Services,1930,United States,Monroe,Louisiana,11866642044,talktous@centurylink.com,http://www.centurylink.com,Above 10000
17,Xerox,/company/xerox/,Public,Information Technology & Services,1906,United States,Norwalk,Connecticut,12039683000,None,https://www.xerox.com/,Above 10000
18,CGI,/company/cgi/,Public,Information Technology & Services,1976,Canada,Montreal,Quebec,15148413200,info@cgi.com,http://www.cgi.com,Above 10000
19,Thomson Reuters,/company/thomson-reuters/,Public,Information Technology & Services,2008,Canada,Toronto,Ontario,14166877500,investor.relations@thomsonreuters.com,http://thomsonreuters.com,Above 10000
20,EPAM Systems,/company/epam-systems/,Public,Information Technology & Services,1993,United States,Newtown,Pennsylvania,12677599000,info@epam.com,https://www.epam.com/,Above 10000
21,NCR,/company/ncr/,Public,Information Technology & Services,1884,United States,Atlanta,Georgia,None,None,https://www.ncr.com/,Above 10000
22,Sopra Steria,/company/sopra-steria/,Public,Information Technology & Services,1968,France,Paris,Paris,None,None,http://www.soprasteria.com,Above 10000
23,SAIC,/company/saic/,Public,Information Technology & Services,2013,United States,Reston,Virginia,18007604332,hrcs@saic.com,http://www.saic.com,Above 10000

In [ ]:
df.to_csv("Companies.csv",index=False)